{ 
  gROOT->Reset(); 
  //gSystem->Load("getCorr_C.so"); //this loads function [Float_t getCorr(Int_t i, Float_t chi)] from external file

  Float_t PI=3.1415927;


  TString currFName = gROOT->GetFile()->GetName();
  cout <<  gROOT->GetFile()->GetName() << endl;
    
  

  //----------------------------------------------------------------------------------------------------//  
  gStyle->SetPalette(1);
  gStyle->SetPadBorderMode(0);
  gStyle->SetPadBorderSize(0);
  gStyle->SetPadRightMargin(0.16);
  gStyle->SetPadLeftMargin(0.13);
  gStyle->SetPadBottomMargin(0.08);
  gStyle->SetLabelOffset(0.015,"xyz");
  gStyle->SetLabelSize(0.042,"xyz");
  gStyle->SetLabelFont(62,"xyz") ;
  //-----------------------//------------------//
  //gStyle->SetTitleX(0.0) //title X location -//
  gStyle->SetTitleW(0.9);  //width-of-title ---//
  gStyle->SetTitleFontSize(0.1); //shifts-title-a-bit-down-
  gStyle->SetTitleFont(42,"t") ;
  gROOT->ForceStyle(); //-needed-to-apply-global-settings-(otherwice-histograms-keep-their-own-settings)--
  //----------------------------------------------------------------------------------------------------//

    //finding-correction-function-

    //gStyle->SetOptStat(111000);
    TCanvas cxy("cxy","",1300,600); //c.SetGrayscale();
    cxy.Divide(2,1);
    cxy.cd(1); hFWxyCCsmear.Draw("colz");
    cxy.cd(2); hFWxySHsmear.Draw("colz");

    Float_t X_shift = hFWxyCCsmear->GetMean(1); //-x-of-the-whole-distribution--
    Float_t Y_shift = hFWxyCCsmear->GetMean(2); //-y-of-the-whole-distribution--


    //-somewhat-older-version--gor-gen7--
    //Float_t xM1 = hFWxyCCsmearXscanM1->GetMean(1); //-x--
    //Float_t xM2 = hFWxyCCsmearXscanM2->GetMean(1); //-x--
    //Float_t xM3 = hFWxyCCsmearXscanM3->GetMean(1); //-x--
    //Float_t xM4 = hFWxyCCsmearXscanM4->GetMean(1); //-x--
    //Float_t xM5 = hFWxyCCsmearXscanM5->GetMean(1); //-x--
    //Float_t xM6 = hFWxyCCsmearXscanM6->GetMean(1); //-x--
    //Float_t xM7 = hFWxyCCsmearXscanM7->GetMean(1); //-x--
    //Float_t xM8 = hFWxyCCsmearXscanM8->GetMean(1); //-x--
    //
    //Float_t yM1 = hFWxyCCsmearYscanM1->GetMean(2); //-y--
    //Float_t yM2 = hFWxyCCsmearYscanM2->GetMean(2); //-y--
    //Float_t yM3 = hFWxyCCsmearYscanM3->GetMean(2); //-y--
    //Float_t yM4 = hFWxyCCsmearYscanM4->GetMean(2); //-y--
    //Float_t yM5 = hFWxyCCsmearYscanM5->GetMean(2); //-y--
    //Float_t yM6 = hFWxyCCsmearYscanM6->GetMean(2); //-y--
    //Float_t yM7 = hFWxyCCsmearYscanM7->GetMean(2); //-y--
    //Float_t yM8 = hFWxyCCsmearYscanM8->GetMean(2); //-y--
    //
    //printf("X_shift  =%6.2f;  Y_shift  =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", X_shift, Y_shift );
    //printf("X_shM[0] =%6.2f;  Y_shM[0] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", X_shift, Y_shift );
    //printf("X_shM[1] =%6.2f;  Y_shM[1] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", xM1, yM1 );
    //printf("X_shM[2] =%6.2f;  Y_shM[2] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", xM2, yM2 );
    //printf("X_shM[3] =%6.2f;  Y_shM[3] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", xM3, yM3 );
    //printf("X_shM[4] =%6.2f;  Y_shM[4] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", xM4, yM4 );
    //printf("X_shM[5] =%6.2f;  Y_shM[5] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", xM5, yM5 );
    //printf("X_shM[6] =%6.2f;  Y_shM[6] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", xM6, yM6 );
    //printf("X_shM[7] =%6.2f;  Y_shM[7] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", xM7, yM7 );
    //printf("X_shM[8] =%6.2f;  Y_shM[8] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", xM8, yM8 );

    //-version-from09.07.2015--which-uses-11-bins-in-META-mult-selected-effectively-the-same0as-innumTrack-Glauber--
    printf("X_shift   =%6.2f;  Y_shift   =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", X_shift, Y_shift );
    printf("X_shM[ 0] =%6.2f;  Y_shM[ 0] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", X_shift, Y_shift );
    printf("X_shM[ 1] =%6.2f;  Y_shM[ 1] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", hFWxyCCsmearM1 ->GetMean(1), hFWxyCCsmearM1 ->GetMean(2) );
    printf("X_shM[ 2] =%6.2f;  Y_shM[ 2] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", hFWxyCCsmearM2 ->GetMean(1), hFWxyCCsmearM2 ->GetMean(2) );
    printf("X_shM[ 3] =%6.2f;  Y_shM[ 3] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", hFWxyCCsmearM3 ->GetMean(1), hFWxyCCsmearM3 ->GetMean(2) );
    printf("X_shM[ 4] =%6.2f;  Y_shM[ 4] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", hFWxyCCsmearM4 ->GetMean(1), hFWxyCCsmearM4 ->GetMean(2) );
    printf("X_shM[ 5] =%6.2f;  Y_shM[ 5] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", hFWxyCCsmearM5 ->GetMean(1), hFWxyCCsmearM5 ->GetMean(2) );
    printf("X_shM[ 6] =%6.2f;  Y_shM[ 6] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", hFWxyCCsmearM6 ->GetMean(1), hFWxyCCsmearM6 ->GetMean(2) );
    printf("X_shM[ 7] =%6.2f;  Y_shM[ 7] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", hFWxyCCsmearM7 ->GetMean(1), hFWxyCCsmearM7 ->GetMean(2) );
    printf("X_shM[ 8] =%6.2f;  Y_shM[ 8] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", hFWxyCCsmearM8 ->GetMean(1), hFWxyCCsmearM8 ->GetMean(2) );
    printf("X_shM[ 9] =%6.2f;  Y_shM[ 9] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", hFWxyCCsmearM9 ->GetMean(1), hFWxyCCsmearM9 ->GetMean(2) );
    printf("X_shM[10] =%6.2f;  Y_shM[10] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", hFWxyCCsmearM10->GetMean(1), hFWxyCCsmearM10->GetMean(2) );
    printf("X_shM[11] =%6.2f;  Y_shM[11] =%6.2f;  \/\/-FW_cuts_autoGenerated-- \n", hFWxyCCsmearM11->GetMean(1), hFWxyCCsmearM11->GetMean(2) );


    //gStyle->SetOptStat("ne");
    TCanvas c("c","",1200, 700);
    c.Divide(6,2);

    //TF1 shape("shape","[0]*( 1. +  2.*[1]*TMath::Cos(x[0]*3.1415/180.) + 2.*[2]*TMath::Cos(2.*x[0]*3.1415/180.) +  [3]*TMath::Cos(x[0]*3.1415/180.))", -180., 180.);
    //TF1 shape("shape",      "( 1. +  2.*[0]*TMath::Cos(x[0]*3.1415/180.) + 2.*[1]*TMath::Cos(2.*x[0]*3.1415/180.) +  [2]*TMath::Sin(x[0]*3.1415/180.))", -180., 180.);

    //-added-cos(3A)----------//
    //TF1 shape("shape",      "( 1. +  2.*[0]*TMath::Cos(x[0]*3.1415/180.) + 2.*[1]*TMath::Cos(2.*x[0]*3.1415/180.) +  [2]*TMath::Sin(x[0]*3.1415/180.) + 2.*[3]*TMath::Cos(3.*x[0]*3.1415/180.))", -180., 180.);
    //-added-cos(3A)-sin(2A)--//
    TF1 shape("shape",      "( 1. +  2.*[0]*TMath::Cos(x[0]*3.1415/180.) + 2.*[1]*TMath::Cos(2.*x[0]*3.1415/180.) +  [2]*TMath::Sin(x[0]*3.1415/180.) + 2.*[3]*TMath::Cos(3.*x[0]*3.1415/180.) + [4]*TMath::Sin(2.*x[0]*3.1415/180.))", -180., 180.);

    hRPAy1.Scale( 90./hRPAy1.GetEntries());  hRPAy1.SetMinimum(0.);
    hRPAy2.Scale( 90./hRPAy2.GetEntries());  hRPAy2.SetMinimum(0.);
    hRPAy3.Scale( 90./hRPAy3.GetEntries());  hRPAy3.SetMinimum(0.);
    hRPAy4.Scale( 90./hRPAy4.GetEntries());  hRPAy4.SetMinimum(0.);
    hRPAy5.Scale( 90./hRPAy5.GetEntries());  hRPAy5.SetMinimum(0.);
    hRPAy6.Scale( 90./hRPAy6.GetEntries());  hRPAy6.SetMinimum(0.);
    hRPAy7.Scale( 90./hRPAy7.GetEntries());  hRPAy7.SetMinimum(0.);
    hRPAy8.Scale( 90./hRPAy8.GetEntries());  hRPAy8.SetMinimum(0.);
    hRPAy9.Scale( 90./hRPAy9.GetEntries());  hRPAy9.SetMinimum(0.);
    hRPAy10.Scale(90./hRPAy10.GetEntries()); hRPAy10.SetMinimum(0.);
    hRPAy11.Scale(90./hRPAy11.GetEntries()); hRPAy11.SetMinimum(0.);

    hRPAy1c.Scale( 90./hRPAy1c.GetEntries() ); hRPAy1c.SetMinimum( 0.); hRPAy1c.SetLineColor(3);
    hRPAy2c.Scale( 90./hRPAy2c.GetEntries() ); hRPAy2c.SetMinimum( 0.); hRPAy2c.SetLineColor(3);
    hRPAy3c.Scale( 90./hRPAy3c.GetEntries() ); hRPAy3c.SetMinimum( 0.); hRPAy3c.SetLineColor(3);
    hRPAy4c.Scale( 90./hRPAy4c.GetEntries() ); hRPAy4c.SetMinimum( 0.); hRPAy4c.SetLineColor(3);
    hRPAy5c.Scale( 90./hRPAy5c.GetEntries() ); hRPAy5c.SetMinimum( 0.); hRPAy5c.SetLineColor(3);
    hRPAy6c.Scale( 90./hRPAy6c.GetEntries() ); hRPAy6c.SetMinimum( 0.); hRPAy6c.SetLineColor(3);
    hRPAy7c.Scale( 90./hRPAy7c.GetEntries() ); hRPAy7c.SetMinimum( 0.); hRPAy7c.SetLineColor(3);
    hRPAy8c.Scale( 90./hRPAy8c.GetEntries() ); hRPAy8c.SetMinimum( 0.); hRPAy8c.SetLineColor(3);
    hRPAy9c.Scale( 90./hRPAy9c.GetEntries() ); hRPAy9c.SetMinimum( 0.); hRPAy9c.SetLineColor(3);
    hRPAy10c.Scale(90./hRPAy10c.GetEntries()); hRPAy10c.SetMinimum(0.); hRPAy10c.SetLineColor(3);
    hRPAy11c.Scale(90./hRPAy11c.GetEntries()); hRPAy11c.SetMinimum(0.); hRPAy11c.SetLineColor(3);

    Float_t  cos1[12]; //-zero-not-used-
    Float_t  cos2[12]; //-zero-not-used-
    Float_t  sin1[12]; //-zero-not-used-
    Float_t  cos3[12]; //-zero-not-used-
    Float_t  sin2[12]; //-zero-not-used-
    
    Char_t ds[100];
    TText txt;

    c.cd( 1); hRPAy1 ->Draw(); hRPAy1 ->Fit("shape"); cos1[ 1] = shape->GetParameter(0); cos2[ 1] = shape->GetParameter(1); sin1[ 1] = shape->GetParameter(2); cos3[ 1] = shape->GetParameter(3); sin2[ 1] = shape->GetParameter(4); sprintf(ds, "ini: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[ 1], cos2[ 1], sin1[ 1], cos3[ 1], sin2[ 1]); txt.DrawTextNDC(0.10, 0.25, ds);
    c.cd( 2); hRPAy2 ->Draw(); hRPAy2 ->Fit("shape"); cos1[ 2] = shape->GetParameter(0); cos2[ 2] = shape->GetParameter(1); sin1[ 2] = shape->GetParameter(2); cos3[ 2] = shape->GetParameter(3); sin2[ 2] = shape->GetParameter(4); sprintf(ds, "ini: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[ 2], cos2[ 2], sin1[ 2], cos3[ 2], sin2[ 2]); txt.DrawTextNDC(0.10, 0.25, ds);
    c.cd( 3); hRPAy3 ->Draw(); hRPAy3 ->Fit("shape"); cos1[ 3] = shape->GetParameter(0); cos2[ 3] = shape->GetParameter(1); sin1[ 3] = shape->GetParameter(2); cos3[ 3] = shape->GetParameter(3); sin2[ 3] = shape->GetParameter(4); sprintf(ds, "ini: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[ 3], cos2[ 3], sin1[ 3], cos3[ 3], sin2[ 3]); txt.DrawTextNDC(0.10, 0.25, ds);
    c.cd( 4); hRPAy4 ->Draw(); hRPAy4 ->Fit("shape"); cos1[ 4] = shape->GetParameter(0); cos2[ 4] = shape->GetParameter(1); sin1[ 4] = shape->GetParameter(2); cos3[ 4] = shape->GetParameter(3); sin2[ 4] = shape->GetParameter(4); sprintf(ds, "ini: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[ 4], cos2[ 4], sin1[ 4], cos3[ 4], sin2[ 4]); txt.DrawTextNDC(0.10, 0.25, ds);
    c.cd( 5); hRPAy5 ->Draw(); hRPAy5 ->Fit("shape"); cos1[ 5] = shape->GetParameter(0); cos2[ 5] = shape->GetParameter(1); sin1[ 5] = shape->GetParameter(2); cos3[ 5] = shape->GetParameter(3); sin2[ 5] = shape->GetParameter(4); sprintf(ds, "ini: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[ 5], cos2[ 5], sin1[ 5], cos3[ 5], sin2[ 5]); txt.DrawTextNDC(0.10, 0.25, ds);
    c.cd( 6); hRPAy6 ->Draw(); hRPAy6 ->Fit("shape"); cos1[ 6] = shape->GetParameter(0); cos2[ 6] = shape->GetParameter(1); sin1[ 6] = shape->GetParameter(2); cos3[ 6] = shape->GetParameter(3); sin2[ 6] = shape->GetParameter(4); sprintf(ds, "ini: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[ 6], cos2[ 6], sin1[ 6], cos3[ 6], sin2[ 6]); txt.DrawTextNDC(0.10, 0.25, ds);
    c.cd( 7); hRPAy7 ->Draw(); hRPAy7 ->Fit("shape"); cos1[ 7] = shape->GetParameter(0); cos2[ 7] = shape->GetParameter(1); sin1[ 7] = shape->GetParameter(2); cos3[ 7] = shape->GetParameter(3); sin2[ 7] = shape->GetParameter(4); sprintf(ds, "ini: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[ 7], cos2[ 7], sin1[ 7], cos3[ 7], sin2[ 7]); txt.DrawTextNDC(0.10, 0.25, ds);
    c.cd( 8); hRPAy8 ->Draw(); hRPAy8 ->Fit("shape"); cos1[ 8] = shape->GetParameter(0); cos2[ 8] = shape->GetParameter(1); sin1[ 8] = shape->GetParameter(2); cos3[ 8] = shape->GetParameter(3); sin2[ 8] = shape->GetParameter(4); sprintf(ds, "ini: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[ 8], cos2[ 8], sin1[ 8], cos3[ 8], sin2[ 8]); txt.DrawTextNDC(0.10, 0.25, ds);
    c.cd( 9); hRPAy9 ->Draw(); hRPAy9 ->Fit("shape"); cos1[ 9] = shape->GetParameter(0); cos2[ 9] = shape->GetParameter(1); sin1[ 9] = shape->GetParameter(2); cos3[ 9] = shape->GetParameter(3); sin2[ 9] = shape->GetParameter(4); sprintf(ds, "ini: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[ 9], cos2[ 9], sin1[ 9], cos3[ 9], sin2[ 9]); txt.DrawTextNDC(0.10, 0.25, ds);
    c.cd(10); hRPAy10->Draw(); hRPAy10->Fit("shape"); cos1[10] = shape->GetParameter(0); cos2[10] = shape->GetParameter(1); sin1[10] = shape->GetParameter(2); cos3[10] = shape->GetParameter(3); sin2[10] = shape->GetParameter(4); sprintf(ds, "ini: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[10], cos2[10], sin1[10], cos3[10], sin2[10]); txt.DrawTextNDC(0.10, 0.25, ds);
    c.cd(11); hRPAy11->Draw(); hRPAy11->Fit("shape"); cos1[11] = shape->GetParameter(0); cos2[11] = shape->GetParameter(1); sin1[11] = shape->GetParameter(2); cos3[11] = shape->GetParameter(3); sin2[11] = shape->GetParameter(4); sprintf(ds, "ini: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[11], cos2[11], sin1[11], cos3[11], sin2[11]); txt.DrawTextNDC(0.10, 0.25, ds);

    printf("=== ======== === results to insert into program === ======== ===\n");
    printf("fRPAy1 ->SetParameters(%8.5f, %8.5f, %8.5f, %8.5f, %8.5f); \/\/-FW_cuts_autoGenerated--\n", cos1[ 1], cos2[ 1], sin1[ 1], cos3[ 1], sin2[ 1]);
    printf("fRPAy2 ->SetParameters(%8.5f, %8.5f, %8.5f, %8.5f, %8.5f); \/\/-FW_cuts_autoGenerated--\n", cos1[ 2], cos2[ 2], sin1[ 2], cos3[ 2], sin2[ 2]);
    printf("fRPAy3 ->SetParameters(%8.5f, %8.5f, %8.5f, %8.5f, %8.5f); \/\/-FW_cuts_autoGenerated--\n", cos1[ 3], cos2[ 3], sin1[ 3], cos3[ 3], sin2[ 3]);
    printf("fRPAy4 ->SetParameters(%8.5f, %8.5f, %8.5f, %8.5f, %8.5f); \/\/-FW_cuts_autoGenerated--\n", cos1[ 4], cos2[ 4], sin1[ 4], cos3[ 4], sin2[ 4]);
    printf("fRPAy5 ->SetParameters(%8.5f, %8.5f, %8.5f, %8.5f, %8.5f); \/\/-FW_cuts_autoGenerated--\n", cos1[ 5], cos2[ 5], sin1[ 5], cos3[ 5], sin2[ 5]);
    printf("fRPAy6 ->SetParameters(%8.5f, %8.5f, %8.5f, %8.5f, %8.5f); \/\/-FW_cuts_autoGenerated--\n", cos1[ 6], cos2[ 6], sin1[ 6], cos3[ 6], sin2[ 6]);
    printf("fRPAy7 ->SetParameters(%8.5f, %8.5f, %8.5f, %8.5f, %8.5f); \/\/-FW_cuts_autoGenerated--\n", cos1[ 7], cos2[ 7], sin1[ 7], cos3[ 7], sin2[ 7]);
    printf("fRPAy8 ->SetParameters(%8.5f, %8.5f, %8.5f, %8.5f, %8.5f); \/\/-FW_cuts_autoGenerated--\n", cos1[ 8], cos2[ 8], sin1[ 8], cos3[ 8], sin2[ 8]);
    printf("fRPAy9 ->SetParameters(%8.5f, %8.5f, %8.5f, %8.5f, %8.5f); \/\/-FW_cuts_autoGenerated--\n", cos1[ 9], cos2[ 9], sin1[ 9], cos3[ 9], sin2[ 9]);
    printf("fRPAy10->SetParameters(%8.5f, %8.5f, %8.5f, %8.5f, %8.5f); \/\/-FW_cuts_autoGenerated--\n", cos1[10], cos2[10], sin1[10], cos3[10], sin2[10]);
    printf("fRPAy11->SetParameters(%8.5f, %8.5f, %8.5f, %8.5f, %8.5f); \/\/-FW_cuts_autoGenerated--\n", cos1[11], cos2[11], sin1[11], cos3[11], sin2[11]);

    TH1F hRPAy1C( "hRPAy1C" ,"hRPAy1C  after immediate corr", 90, -180., 180);
    TH1F hRPAy2C( "hRPAy2C" ,"hRPAy2C  after immediate corr", 90, -180., 180);
    TH1F hRPAy3C( "hRPAy3C" ,"hRPAy3C  after immediate corr", 90, -180., 180);
    TH1F hRPAy4C( "hRPAy4C" ,"hRPAy4C  after immediate corr", 90, -180., 180);
    TH1F hRPAy5C( "hRPAy5C" ,"hRPAy5C  after immediate corr", 90, -180., 180);
    TH1F hRPAy6C( "hRPAy6C" ,"hRPAy6C  after immediate corr", 90, -180., 180);
    TH1F hRPAy7C( "hRPAy7C" ,"hRPAy7C  after immediate corr", 90, -180., 180);
    TH1F hRPAy8C( "hRPAy8C" ,"hRPAy8C  after immediate corr", 90, -180., 180);
    TH1F hRPAy9C( "hRPAy9C" ,"hRPAy9C  after immediate corr", 90, -180., 180);
    TH1F hRPAy10C("hRPAy10C","hRPAy10C after immediate corr", 90, -180., 180);
    TH1F hRPAy11C("hRPAy11C","hRPAy11C after immediate corr", 90, -180., 180);

    Float_t phi_r;
    for(Int_t phi=-180; phi<180; phi++){
       phi_r = phi/180.*3.1415;
       shape->SetParameters(cos1[ 1], cos2[ 1], sin1[ 1], cos3[ 1], sin2[ 1]); hRPAy1C->Fill(phi, 0.25/(shape->Eval(phi)) ); //
       shape->SetParameters(cos1[ 2], cos2[ 2], sin1[ 2], cos3[ 2], sin2[ 2]); hRPAy2C->Fill(phi, 0.25/(shape->Eval(phi)) ); //
       shape->SetParameters(cos1[ 3], cos2[ 3], sin1[ 3], cos3[ 3], sin2[ 3]); hRPAy3C->Fill(phi, 0.25/(shape->Eval(phi)) ); //
       shape->SetParameters(cos1[ 4], cos2[ 4], sin1[ 4], cos3[ 4], sin2[ 4]); hRPAy4C->Fill(phi, 0.25/(shape->Eval(phi)) ); //
       shape->SetParameters(cos1[ 5], cos2[ 5], sin1[ 5], cos3[ 5], sin2[ 5]); hRPAy5C->Fill(phi, 0.25/(shape->Eval(phi)) ); //
       shape->SetParameters(cos1[ 6], cos2[ 6], sin1[ 6], cos3[ 6], sin2[ 6]); hRPAy6C->Fill(phi, 0.25/(shape->Eval(phi)) ); //
       shape->SetParameters(cos1[ 7], cos2[ 7], sin1[ 7], cos3[ 7], sin2[ 7]); hRPAy7C->Fill(phi, 0.25/(shape->Eval(phi)) ); //
       shape->SetParameters(cos1[ 8], cos2[ 8], sin1[ 8], cos3[ 8], sin2[ 8]); hRPAy8C->Fill(phi, 0.25/(shape->Eval(phi)) ); //
       shape->SetParameters(cos1[ 9], cos2[ 9], sin1[ 9], cos3[ 9], sin2[ 9]); hRPAy8C->Fill(phi, 0.25/(shape->Eval(phi)) ); //
       shape->SetParameters(cos1[10], cos2[10], sin1[10], cos3[10], sin2[10]); hRPAy8C->Fill(phi, 0.25/(shape->Eval(phi)) ); //
       shape->SetParameters(cos1[11], cos2[11], sin1[11], cos3[11], sin2[11]); hRPAy8C->Fill(phi, 0.25/(shape->Eval(phi)) ); //
    }

    /*
    c.cd(1); hRPAy1c->Draw("same"); hRPAy1C->Draw("same");
    c.cd(2); hRPAy2c->Draw("same"); hRPAy2C->Draw("same");
    c.cd(3); hRPAy3c->Draw("same"); hRPAy3C->Draw("same");
    c.cd(4); hRPAy4c->Draw("same"); hRPAy4C->Draw("same");
    c.cd(5); hRPAy5c->Draw("same"); hRPAy5C->Draw("same");
    c.cd(6); hRPAy6c->Draw("same"); hRPAy6C->Draw("same");
    */

    TCanvas C("C","",1200, 700);
    C.Divide(6,2);
    C.cd( 1); hRPAy1c ->Draw("same");  hRPAy1c ->Fit("shape"); cos1[ 1] = shape->GetParameter(0); cos2[ 1] = shape->GetParameter(1); sin1[ 1] = shape->GetParameter(2); cos3[ 1] = shape->GetParameter(3); sin2[ 1] = shape->GetParameter(4); sprintf(ds, "fin: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[ 1], cos2[ 1], sin1[ 1], cos3[ 1], sin2[ 1]); txt.DrawTextNDC(0.10, 0.15, ds);
    C.cd( 2); hRPAy2c ->Draw("same");  hRPAy2c ->Fit("shape"); cos1[ 2] = shape->GetParameter(0); cos2[ 2] = shape->GetParameter(1); sin1[ 2] = shape->GetParameter(2); cos3[ 2] = shape->GetParameter(3); sin2[ 2] = shape->GetParameter(4); sprintf(ds, "fin: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[ 2], cos2[ 2], sin1[ 2], cos3[ 2], sin2[ 2]); txt.DrawTextNDC(0.10, 0.15, ds);
    C.cd( 3); hRPAy3c ->Draw("same");  hRPAy3c ->Fit("shape"); cos1[ 3] = shape->GetParameter(0); cos2[ 3] = shape->GetParameter(1); sin1[ 3] = shape->GetParameter(2); cos3[ 3] = shape->GetParameter(3); sin2[ 3] = shape->GetParameter(4); sprintf(ds, "fin: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[ 3], cos2[ 3], sin1[ 3], cos3[ 3], sin2[ 3]); txt.DrawTextNDC(0.10, 0.15, ds);
    C.cd( 4); hRPAy4c ->Draw("same");  hRPAy4c ->Fit("shape"); cos1[ 4] = shape->GetParameter(0); cos2[ 4] = shape->GetParameter(1); sin1[ 4] = shape->GetParameter(2); cos3[ 4] = shape->GetParameter(3); sin2[ 4] = shape->GetParameter(4); sprintf(ds, "fin: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[ 4], cos2[ 4], sin1[ 4], cos3[ 4], sin2[ 4]); txt.DrawTextNDC(0.10, 0.15, ds);
    C.cd( 5); hRPAy5c ->Draw("same");  hRPAy5c ->Fit("shape"); cos1[ 5] = shape->GetParameter(0); cos2[ 5] = shape->GetParameter(1); sin1[ 5] = shape->GetParameter(2); cos3[ 5] = shape->GetParameter(3); sin2[ 5] = shape->GetParameter(4); sprintf(ds, "fin: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[ 5], cos2[ 5], sin1[ 5], cos3[ 5], sin2[ 5]); txt.DrawTextNDC(0.10, 0.15, ds);
    C.cd( 6); hRPAy6c ->Draw("same");  hRPAy6c ->Fit("shape"); cos1[ 6] = shape->GetParameter(0); cos2[ 6] = shape->GetParameter(1); sin1[ 6] = shape->GetParameter(2); cos3[ 6] = shape->GetParameter(3); sin2[ 6] = shape->GetParameter(4); sprintf(ds, "fin: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[ 6], cos2[ 6], sin1[ 6], cos3[ 6], sin2[ 6]); txt.DrawTextNDC(0.10, 0.15, ds);
    C.cd( 7); hRPAy7c ->Draw("same");  hRPAy7c ->Fit("shape"); cos1[ 7] = shape->GetParameter(0); cos2[ 7] = shape->GetParameter(1); sin1[ 7] = shape->GetParameter(2); cos3[ 7] = shape->GetParameter(3); sin2[ 7] = shape->GetParameter(4); sprintf(ds, "fin: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[ 7], cos2[ 7], sin1[ 7], cos3[ 7], sin2[ 7]); txt.DrawTextNDC(0.10, 0.15, ds);
    C.cd( 8); hRPAy8c ->Draw("same");  hRPAy8c ->Fit("shape"); cos1[ 8] = shape->GetParameter(0); cos2[ 8] = shape->GetParameter(1); sin1[ 8] = shape->GetParameter(2); cos3[ 8] = shape->GetParameter(3); sin2[ 8] = shape->GetParameter(4); sprintf(ds, "fin: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[ 8], cos2[ 8], sin1[ 8], cos3[ 8], sin2[ 8]); txt.DrawTextNDC(0.10, 0.15, ds);
    C.cd( 9); hRPAy9c ->Draw("same");  hRPAy9c ->Fit("shape"); cos1[ 9] = shape->GetParameter(0); cos2[ 9] = shape->GetParameter(1); sin1[ 9] = shape->GetParameter(2); cos3[ 9] = shape->GetParameter(3); sin2[ 9] = shape->GetParameter(4); sprintf(ds, "fin: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[ 9], cos2[ 9], sin1[ 9], cos3[ 9], sin2[ 9]); txt.DrawTextNDC(0.10, 0.15, ds);
    C.cd(10); hRPAy10c->Draw("same");  hRPAy10c->Fit("shape"); cos1[10] = shape->GetParameter(0); cos2[10] = shape->GetParameter(1); sin1[10] = shape->GetParameter(2); cos3[10] = shape->GetParameter(3); sin2[10] = shape->GetParameter(4); sprintf(ds, "fin: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[10], cos2[10], sin1[10], cos3[10], sin2[10]); txt.DrawTextNDC(0.10, 0.15, ds);
    C.cd(11); hRPAy11c->Draw("same");  hRPAy11c->Fit("shape"); cos1[11] = shape->GetParameter(0); cos2[11] = shape->GetParameter(1); sin1[11] = shape->GetParameter(2); cos3[11] = shape->GetParameter(3); sin2[11] = shape->GetParameter(4); sprintf(ds, "fin: c1=%4.3f c2=%4.3f s1=%4.3f c3=%4.3f s2=%4.3f", cos1[11], cos2[11], sin1[11], cos3[11], sin2[11]); txt.DrawTextNDC(0.10, 0.15, ds);

  }



}



